const now = Math.floor(Date.now() / 1000);
const day = 60 * 60 * 24;
const nextRefreshAt = (() => {
  const date = new Date(now * 1000);
  date.setMinutes(10, 0, 0);
  if (date.getTime() <= now * 1000) {
    date.setHours(date.getHours() + 1);
  }
  return Math.floor(date.getTime() / 1000);
})();

const prizes = [
  { position: 1, reward: "500 EUR + destacada en portada" },
  { position: 2, reward: "250 EUR + pack premium" },
  { position: 3, reward: "100 EUR + pack premium" },
  { position: 4, reward: "50 EUR" },
  { position: 5, reward: "25 EUR" },
  { position: 6, reward: "10 EUR" },
  { position: 7, reward: "10 EUR" },
  { position: 8, reward: "10 EUR" },
  { position: 9, reward: "10 EUR" },
  { position: 10, reward: "10 EUR" },
];

const ranking = [
  {
    id: 1001,
    user_id: 1001,
    position: 1,
    username: "Mateito Clips",
    user_image: "https://i.pravatar.cc/120?img=11",
    video_title: "Mi mejor clip del mes",
    video_id: "tiktok-1001",
    video_cover_image_url: "https://picsum.photos/seed/tk1001/400/700",
    video_share_url: "https://www.tiktok.com/@mateito/video/1001",
    view_count: 98124,
    like_count: 11203,
    comment_count: 684,
    share_count: 2190,
    reward: "500 EUR + destacada en portada",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 8,
  },
  {
    id: 1002,
    user_id: 1002,
    position: 2,
    username: "Fran Editz",
    user_image: "https://i.pravatar.cc/120?img=12",
    video_title: "Edit viral de MateoZ",
    video_id: "tiktok-1002",
    video_cover_image_url: "https://picsum.photos/seed/tk1002/400/700",
    video_share_url: "https://www.tiktok.com/@fran/video/1002",
    view_count: 87210,
    like_count: 9402,
    comment_count: 522,
    share_count: 1875,
    reward: "250 EUR + pack premium",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 7,
  },
  {
    id: 1003,
    user_id: 1003,
    position: 3,
    username: "Luna Gaming",
    user_image: "https://i.pravatar.cc/120?img=13",
    video_title: "Reaccion brutal en directo",
    video_id: "tiktok-1003",
    video_cover_image_url: "https://picsum.photos/seed/tk1003/400/700",
    video_share_url: "https://www.tiktok.com/@luna/video/1003",
    view_count: 75642,
    like_count: 8120,
    comment_count: 470,
    share_count: 1401,
    reward: "100 EUR + pack premium",
    status: "approved",
    review_note: null,
    associated_at: now - day * 6,
  },
  {
    id: 1004,
    user_id: 1004,
    position: 4,
    username: "Nico Shorts",
    user_image: "https://i.pravatar.cc/120?img=14",
    video_title: "Clip corto pero explosivo",
    video_id: "tiktok-1004",
    video_cover_image_url: "https://picsum.photos/seed/tk1004/400/700",
    video_share_url: "https://www.tiktok.com/@nico/video/1004",
    view_count: 70110,
    like_count: 7104,
    comment_count: 399,
    share_count: 1205,
    reward: "50 EUR",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 5,
  },
  {
    id: 1005,
    user_id: 1005,
    position: 5,
    username: "Sara Plays",
    user_image: "https://i.pravatar.cc/120?img=15",
    video_title: "Compilado de mejores momentos",
    video_id: "tiktok-1005",
    video_cover_image_url: "https://picsum.photos/seed/tk1005/400/700",
    video_share_url: "https://www.tiktok.com/@sara/video/1005",
    view_count: 65550,
    like_count: 6502,
    comment_count: 350,
    share_count: 1099,
    reward: "25 EUR",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 5,
  },
  {
    id: 1006,
    user_id: 1006,
    position: 6,
    username: "Alex Stream",
    user_image: "https://i.pravatar.cc/120?img=16",
    video_title: "Fails y risas del stream",
    video_id: "tiktok-1006",
    video_cover_image_url: "https://picsum.photos/seed/tk1006/400/700",
    video_share_url: "https://www.tiktok.com/@alex/video/1006",
    view_count: 61200,
    like_count: 5880,
    comment_count: 310,
    share_count: 950,
    reward: "10 EUR",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 4,
  },
  {
    id: 1007,
    user_id: 1007,
    position: 7,
    username: "RokoTV",
    user_image: "https://i.pravatar.cc/120?img=17",
    video_title: "Top jugadas de la semana",
    video_id: "tiktok-1007",
    video_cover_image_url: "https://picsum.photos/seed/tk1007/400/700",
    video_share_url: "https://www.tiktok.com/@roko/video/1007",
    view_count: 58040,
    like_count: 5100,
    comment_count: 281,
    share_count: 901,
    reward: "10 EUR",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 4,
  },
  {
    id: 1008,
    user_id: 1008,
    position: 8,
    username: "Pixel Queen",
    user_image: "https://i.pravatar.cc/120?img=18",
    video_title: "Montaje con mejor retencion",
    video_id: "tiktok-1008",
    video_cover_image_url: "https://picsum.photos/seed/tk1008/400/700",
    video_share_url: "https://www.tiktok.com/@pixel/video/1008",
    view_count: 56120,
    like_count: 4820,
    comment_count: 255,
    share_count: 860,
    reward: "10 EUR",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 3,
  },
  {
    id: 1009,
    user_id: 1009,
    position: 9,
    username: "Cris Esports",
    user_image: "https://i.pravatar.cc/120?img=19",
    video_title: "Resumen competitivo",
    video_id: "tiktok-1009",
    video_cover_image_url: "https://picsum.photos/seed/tk1009/400/700",
    video_share_url: "https://www.tiktok.com/@cris/video/1009",
    view_count: 54090,
    like_count: 4600,
    comment_count: 231,
    share_count: 812,
    reward: "10 EUR",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 3,
  },
  {
    id: 1010,
    user_id: 1010,
    position: 10,
    username: "Javi Clipz",
    user_image: "https://i.pravatar.cc/120?img=20",
    video_title: "El clip mas loco del dia",
    video_id: "tiktok-1010",
    video_cover_image_url: "https://picsum.photos/seed/tk1010/400/700",
    video_share_url: "https://www.tiktok.com/@javi/video/1010",
    view_count: 52020,
    like_count: 4412,
    comment_count: 220,
    share_count: 790,
    reward: "10 EUR",
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 3,
  },
  {
    id: 1011,
    user_id: 1011,
    position: 11,
    username: "ClipsDelBoss",
    user_image: "https://i.pravatar.cc/120?img=21",
    video_title: "Top reacciones del chat",
    video_id: "tiktok-1011",
    video_cover_image_url: "https://picsum.photos/seed/tk1011/400/700",
    video_share_url: "https://www.tiktok.com/@boss/video/1011",
    view_count: 48100,
    like_count: 3988,
    comment_count: 201,
    share_count: 733,
    reward: undefined,
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 2,
  },
  {
    id: 1012,
    user_id: 1012,
    position: 12,
    username: "TwitchCutz",
    user_image: "https://i.pravatar.cc/120?img=22",
    video_title: "Storytime del directo",
    video_id: "tiktok-1012",
    video_cover_image_url: "https://picsum.photos/seed/tk1012/400/700",
    video_share_url: "https://www.tiktok.com/@cutz/video/1012",
    view_count: 46220,
    like_count: 3772,
    comment_count: 192,
    share_count: 710,
    reward: undefined,
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 2,
  },
  {
    id: 1013,
    user_id: 1013,
    position: 13,
    username: "Mari Highlights",
    user_image: "https://i.pravatar.cc/120?img=23",
    video_title: "Momento troll del stream",
    video_id: "tiktok-1013",
    video_cover_image_url: "https://picsum.photos/seed/tk1013/400/700",
    video_share_url: "https://www.tiktok.com/@mari/video/1013",
    view_count: 44100,
    like_count: 3550,
    comment_count: 180,
    share_count: 684,
    reward: undefined,
    status: "pending_review",
    review_note: null,
    associated_at: now - day * 2,
  },
  {
    id: 1014,
    user_id: 1014,
    position: 14,
    username: "ZoneStreamer",
    user_image: "https://i.pravatar.cc/120?img=24",
    video_title: "Reaccion final del torneo",
    video_id: "tiktok-1014",
    video_cover_image_url: "https://picsum.photos/seed/tk1014/400/700",
    video_share_url: "https://www.tiktok.com/@zone/video/1014",
    view_count: 42010,
    like_count: 3344,
    comment_count: 170,
    share_count: 645,
    reward: undefined,
    status: "pending_review",
    review_note: null,
    associated_at: now - day,
  },
  {
    id: 1015,
    user_id: 1015,
    position: 15,
    username: "Kira Legends",
    user_image: "https://i.pravatar.cc/120?img=25",
    video_title: "El ultimo clip viral",
    video_id: "tiktok-1015",
    video_cover_image_url: "https://picsum.photos/seed/tk1015/400/700",
    video_share_url: "https://www.tiktok.com/@kira/video/1015",
    view_count: 39880,
    like_count: 3200,
    comment_count: 162,
    share_count: 600,
    reward: undefined,
    status: "pending_review",
    review_note: null,
    associated_at: now - day,
  },
];

const snapshots = [
  {
    id: 2001,
    leaderboard_id: 777,
    position: 5,
    user_id: 9001,
    username: "Fran Original",
    user_image: "https://i.pravatar.cc/120?img=31",
    video_id: "old-9001",
    video_title: "Video descalificado por contenido no apto",
    video_cover_image_url: "https://picsum.photos/seed/disq1/400/700",
    video_share_url: "https://www.tiktok.com/@franoriginal/video/9001",
    view_count: 69000,
    like_count: 7001,
    comment_count: 401,
    share_count: 1100,
    reward: "25 EUR",
    status: "disqualified",
    review_note: "Video descalificado por incumplir las normas de la promocion.",
    created_at: now - day,
    updated_at: now - 3600,
  },
  {
    id: 2002,
    leaderboard_id: 777,
    position: 8,
    user_id: 9002,
    username: "ClipHunter",
    user_image: "https://i.pravatar.cc/120?img=32",
    video_id: "old-9002",
    video_title: "Video duplicado eliminado",
    video_cover_image_url: "https://picsum.photos/seed/disq2/400/700",
    video_share_url: "https://www.tiktok.com/@cliphunter/video/9002",
    view_count: 57000,
    like_count: 4900,
    comment_count: 260,
    share_count: 880,
    reward: "10 EUR",
    status: "disqualified",
    review_note: "Video duplicado. El premio se reasigna al siguiente usuario elegible.",
    created_at: now - day,
    updated_at: now - 1800,
  },
];

export const mockTikTokLeaderboards = {
  active: [
    {
      id: 777,
      title: "Leaderboard de verano",
      description:
        "Mock temporal para revisar la UI completa con muchos participantes, videos, premios y reasignaciones.",
      start_at: now - day * 10,
      end_at: now + day * 4,
      status: "active",
      finalized_at: null,
      has_reallocation: true,
      reallocation_count: 2,
      review_notes:
        "Mock temporal para frontend. Dos puestos muestran reasignacion por descalificacion.",
      created_at: now - day * 10,
      updated_at: now - 600,
      prizes,
      ranking: ranking.slice(0, 10),
      is_active: true,
      next_refresh_at: nextRefreshAt,
    },
  ],
  past: [],
};

export const mockTikTokLeaderboardDetail = {
  id: 777,
  title: "Leaderboard de verano",
  description:
    "Mock temporal para revisar la UI completa con muchos participantes, videos, premios y reasignaciones.",
  start_at: now - day * 10,
  end_at: now + day * 4,
  status: "active",
  finalized_at: null,
  has_reallocation: true,
  reallocation_count: 2,
  review_notes:
    "Mock temporal para frontend. Dos puestos muestran reasignacion por descalificacion.",
  created_at: now - day * 10,
  updated_at: now - 600,
  prizes,
  ranking,
  snapshots,
  is_active: true,
  next_refresh_at: nextRefreshAt,
};
